{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
 {{- if .Values.sename}}
 name: {{ .Values.name }}-map
 {{- else }}
 name: {{.Values.name}}
 {{- end }} 
data:
{{.Values.env.config | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
 name: {{ .Values.name }}-secret
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-dockercfg
  annotations:
    harness.io/skip-versioning: true
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.name }}-deployment
 {{- else }}
 name: {{.Values.name}}-deployment
 {{- end }} 
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.name }}-dep
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-temp
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{ .Values.name }}-dockercfg
      {{- end}}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        {{- if or .Values.env.config .Values.env.secrets}}
        imagePullPolicy: Always
        envFrom:
        {{- if .Values.env.config}}
        - configMapRef:
            name: {{ .Values.name }}
        {{- end}}
        {{- if .Values.env.secrets}}
        - secretRef:
            name: {{ .Values.name }}
        {{- end}}
        {{- end}}
