apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress-router
 annotations:
   kubernetes.io/ingress.class: nginx
   kubernetes.io/ingress.global-static-ip-name: "bootcamp-static-ip"
spec:
  rules:
  - host: cie-bootcamp.co.uk
    http:
     paths:
     - backend:
          serviceName: payment-service-svc
          servicePort: 8080
